"""subjects linked with class

Revision ID: 1dcf40a608ec
Revises: d47e878d5035
Create Date: 2025-09-06 17:02:10.791519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcf40a608ec'
down_revision: Union[str, None] = 'd47e878d5035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('class_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subject', 'classtable', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'class_id')
    # ### end Alembic commands ###
