"""references on classtable now ON DELETE CASCADE

Revision ID: 253bf9d826a9
Revises: 484d77ca6e13
Create Date: 2025-10-14 14:33:10.754346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253bf9d826a9'
down_revision: Union[str, Sequence[str], None] = '484d77ca6e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('classchat_ibfk_1'), 'classchat', type_='foreignkey')
    op.create_foreign_key(None, 'classchat', 'classtable', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subject_ibfk_1'), 'subject', type_='foreignkey')
    op.create_foreign_key(None, 'subject', 'classtable', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.create_foreign_key(op.f('subject_ibfk_1'), 'subject', 'classtable', ['class_id'], ['id'])
    op.drop_constraint(None, 'classchat', type_='foreignkey')
    op.create_foreign_key(op.f('classchat_ibfk_1'), 'classchat', 'classtable', ['class_id'], ['id'])
    # ### end Alembic commands ###
