"""chat_id in classchat now unique

Revision ID: 34b1fb63d75b
Revises: a8691139f9f6
Create Date: 2025-09-18 19:24:42.349423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b1fb63d75b'
down_revision: Union[str, Sequence[str], None] = 'a8691139f9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classchat', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classchat', type_='unique')
    # ### end Alembic commands ###
