"""chat_id in classchat now BIGINT

Revision ID: 37e70b303a0a
Revises: 34b1fb63d75b
Create Date: 2025-09-18 20:50:04.986114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37e70b303a0a'
down_revision: Union[str, Sequence[str], None] = '34b1fb63d75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classchat', 'chat_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classchat', 'chat_id',
               existing_type=sa.BIGINT(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
