"""homework table now has week column

Revision ID: 427769071448
Revises: 5d657e0c8e35
Create Date: 2025-09-30 18:22:12.599220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427769071448'
down_revision: Union[str, Sequence[str], None] = '5d657e0c8e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('week', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'week')
    # ### end Alembic commands ###
