"""homework table now has year column

Revision ID: 484d77ca6e13
Revises: 427769071448
Create Date: 2025-09-30 18:53:45.342504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484d77ca6e13'
down_revision: Union[str, Sequence[str], None] = '427769071448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'year')
    # ### end Alembic commands ###
