"""homework table now has column attachment url

Revision ID: 5d657e0c8e35
Revises: 37e70b303a0a
Create Date: 2025-09-27 21:11:50.219083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d657e0c8e35'
down_revision: Union[str, Sequence[str], None] = '37e70b303a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('attachment_url', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'attachment_url')
    # ### end Alembic commands ###
