"""init revision

Revision ID: f07a99be64fc
Revises: 
Create Date: 2025-09-06 10:41:15.407121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07a99be64fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classtable',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('creator_username', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subject',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('weekday_number', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Enum('FIRST', 'SECOND', 'NOT_GROUPED', name='groupnumberenum'), server_default=sa.text("'NOT_GROUPED'"), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classtable.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework',
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classtable.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework')
    op.drop_table('lesson')
    op.drop_table('subject')
    op.drop_table('classtable')
    # ### end Alembic commands ###
